[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.15.90"

# Need an override on jaeger-lib as it has a ^0.8.0 contraint on client_golang.
[[override]]
  name = "github.com/uber/jaeger-lib"
  version = ">=v1.5.0"

# Pin to master branch until there is a more recent stable release:
#   https://github.com/prometheus/client_golang/issues/375
[[override]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/alertmanager"
  revision = "fb713f6d8239b57c646cae30f78e8b4b8861a1aa"

# Since Cortex is heavily based on Prometheus packages, we want
# to track upstream master quite closely, without being constrained
# to the latest Prometheus release. This means we get various bug
# fixes and features earlier, and makes necessary refactorings upon
# vendor updates less huge (if updated frequently).
[[constraint]]
  name = "github.com/prometheus/prometheus"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/tsdb"
  version = "0.6.1"

[[override]]
  name = "k8s.io/client-go"
  revision = "a47917edff34c2c3f7be36398e3ebad6011ce05c"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "2b1284ed4c93a43499e781493253e2ac5959c4fd"

[[override]]
  name = "k8s.io/api"
  revision = "05914d821849570fba9eacfb29466f2d8d3cd229"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "a1a2da0aba294fe51ba47119e652ff2f08a78afb"

[[override]]
  name = "github.com/weaveworks/mesh"
  revision = "5015f896ab62d3e9fe757456c757521ce0c3faff"

# bbolt version tags are not understood by dep, so we need to manually specify them.
[[constraint]]
  name = "github.com/etcd-io/bbolt"
  version = "v1.3.1-etcd.8"

# Need googleapis/google-cloud-go@c750310, which isn't in a release yet, to fix
# googleapis/google-cloud-go#1242.  And needs to be an override to satisfy
# "github.com/fsouza/fake-gcs-server.
[[override]]
  name = "cloud.google.com/go"
  branch = "master"

# Depends on specific version of cloud.google.com/go, and we need master of that.
# So override to latest version.
[[override]]
  version = "1.3.0"
  name = "github.com/fsouza/fake-gcs-server"
<<<<<<< HEAD
=======
[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"
>>>>>>> 37aff0fc... import google oath for bigtable jwt
